### ISSUE TITLE
triplet 데이터 만들 때

### ISSUE THREAD

**Issue by namghiwook** [jeong-tae/DeepFashion-Tensorflow#2]
q, p, n 을 만드는데 
n 이야 같은 카테고리의 다른 옷이면 되지만
q 와 p 는 같은 옷인데 다른 사진으로 해야하지 않나요?

**Comment by jeong-tae** [comment]
원래 데이터셋 중에 shop-retrieval 데이터셋은 q, p, n 세개의 레이블을 가지고 있습니다만, 여기서 사용하는 데이터셋은 attribute prediction 데이터셋만 이용하고 있어서 https://github.com/jeong-tae/DeepFashion-Tensorflow/blob/master/data_loader.py#L128-L129
와 같이 같은 카테고리에 속하는 옷은 p로, 아닌 것은 n으로 하여 학습시켰습니다.
